version: '3.8'

services:
  ip-watcher:
    build: .
    container_name: ip-watcher
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - ./data:/data
    environment:
      - TZ=Etc/UTC
