ip_ranges:
  - "192.168.1.0/24"
  - "10.0.0.1-10.0.0.50"

deep_scan_schedule: "0 2 * * *" # 2 AM daily

ping_sweep_interval: 300 # 5 minutes

mqtt:
  broker_url: "mqtt://localhost"
  topic: "homeassistant/device_tracker/ip_watcher"
  username: ""
  password: ""
